# Generated by Django 3.2.5 on 2021-07-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210725_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='codes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
